site_name: springboot-handbook
site_description: springboot手册
site_author: 'kpn2021'
site_url: 'https://kpn2021.github.io/springboot-handbook/'
copyright: Copyright &copy; 2022  <a href="https://github.com/kpn2021/">keeplearn</a>
repo_url: 'https://github.com/kpn2021/springboot-handbook'

# 文档结构配置
nav:
- Home: index.md
- GettingStarted:
  - 构建SpringBoot: usage.md
  - Tutorial: tutorial.md
- 常用技巧:
  - IP定位地理位置: third/iptool.md  
  - ZooKeeper操作工具: third/zktool.md
  - SpringBoot配置文件加密工具: third/jasypt.md
- About: about.md

# 使用主题要安装依赖 pip install mkdocs-material
theme:
  name: material
  language: 'zh'
